python main.py \
    --seed 42 \
    --dataset voc \
    --devices '0' \
    --batch_size 64 \
    --check_val_every_n_epoch 20 \
    --name 'test' \
    --config 'configs/config.yaml' \
    --watch_model \
    --project 'debug' \
    --evaluator 'mbo' \
    --model 'dinosaur' \
    --enable_logger \
