python main_bsa.py \
--dataset birds \
--evaluate iou \
--monitor avg_IoU \
--gpus 2 \
--device '1, 7' \
--batch_size 32 \
--num_slots 3 \
--log_name 'test_BOQSA' \
--check_val_every_n_epoch 100 \
--is_logger_enabled \
--seed 42 \
--init_method 'embedding' \
--truncate 'bi-level' \